sudo: false
cache:
  directories:
  - $HOME/.gradle
services:
- redis
- mongodb
- cassandra
jdk:
- oraclejdk7
install: false
script: ./gradlew check
env:
  global:
  - TERM=dumb
  - MALLOC_ARENA_MAX=1
  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=256m -XX:+CMSClassUnloadingEnabled"
notifications:
  slack:
    secure: hC6+UTQWYI/McFA1GjLMYBaDOF4vdaWFE5gZfDbygIxe1aImevhZaTLYxxJAsogrG2oKE3rrdnBXjriEB6j8cq1oNpLFge5JAQBAITKDHm7H+Bb1TVyq8qwRNozg3GGLOKWmradk98Up6yzu8H9iX4l6+gOob+a5X+FciVdW9HaBQCuWowlKJgZQtFEMcvFhgWjHYyBcGa7H3rewj0HW55ipwRbz4LDmoFEszFUKnJFCZEScUzrplPGIUkXHfBTgzhfobEEpvR+shUkBhs3hL0N2Qc0/4co3C5u8wQ+xSLUfd2EZSRcSPWJp1T/BlQrlnJllC1kw7rO20FGnEx0aoZ1LgRqqB/vCV2InPD/dW26BUKXYVEUXKdZD4CJ8RRZVVioMRwwBSBWxwNDKDqwWCr2Wy7J2qhuUlaMpAdZSIfFn0mNObEDlGppi6SyIFqkI/kNPHMkLidS7O4Eq+Cao/9hSmbBEAtsSLBakOvSQ5iwZjjitFX1qfxsFRqZvCycWAkYHku9SqzqEWKK5YdunpnE9I+b9b/+2OOhV1l81/7JchuFovB2iLkGDDXFVL5ST5M+YhYYLLRDJaPCJYGLro/2PBNOTAHSEyX/LHYTd5ZsYE7riJ+sFDUe/wNN1z5+V7U7TAPqWW1cZyQzGsCEX9tYNGU4QSR6nJEV/cqxrrqs=
