sudo: false
# cache:
#   directories:
#   - $HOME/.gradle
services:
- redis
- mongodb
- cassandra
jdk:
- oraclejdk7
install: false
script: ./gradlew check -i
env:
  global:
  - TERM=dumb
  - MALLOC_ARENA_MAX=1
  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=256m -XX:+CMSClassUnloadingEnabled"